basePath: /api/v1
definitions:
  models.Authentication:
    properties:
      accessToken:
        description: |-
          The access token to use for the API
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        type: string
      expiresIn:
        description: |-
          The duration of the token (in seconds).
          example: 3600
        type: integer
      tokenType:
        description: |-
          The type of the token.
          example: Bearer
        type: string
    type: object
  models.Party:
    properties:
      creation:
        description: |-
          The creation date of the party.
          example: 2021-10-10T12:00:00Z
        type: string
      id:
        description: |-
          The ID of the party.
          It is a random string of 69 characters.
        type: string
      leader:
        allOf:
        - $ref: '#/definitions/models.Player'
        description: The leader of the party.
      players:
        description: The list of players in the party.
        items:
          $ref: '#/definitions/models.Player'
        type: array
      settings:
        allOf:
        - $ref: '#/definitions/models.Settings'
        description: The settings of the party.
    type: object
  models.Player:
    properties:
      discordID:
        description: |-
          The player's Discord ID.
          example: "385441179069579265"
        type: string
      name:
        description: |-
          The player's name.
          example: Notch
        type: string
      uuid:
        description: |-
          The player's UUID.
          example: 069a79f4-44e9-4726-a5be-fca90e38aaf5
        type: string
    type: object
  models.Settings:
    properties:
      listed:
        description: |-
          Whether the party can be listed or not.
          example: true
        type: boolean
      maxPlayers:
        description: |-
          The maximum number of players in the party.
          example: 10
        type: integer
      public:
        description: |-
          Whether the party is public or not.
          If false can only be joined by invite.
          example: true
        type: boolean
    type: object
info:
  contact:
    name: Lambda Discord
    url: https://discord.gg/J23U4YEaAr
  description: This is the API for the Lambda Discord RPC handler
  license:
    name: GNU General Public License v3.0
    url: https://www.gnu.org/licenses/gpl-3.0.html
  title: Lambda RPC API
  version: "1.0"
paths:
  /party/create:
    post:
      consumes:
      - application/json
      description: Create a new party
      parameters:
      - description: Settings
        in: body
        name: Settings
        schema:
          $ref: '#/definitions/models.Settings'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Party'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/models.Party'
      security:
      - Bearer: []
      summary: Create a new party
      tags:
      - Party
  /party/join:
    put:
      consumes:
      - application/json
      description: Join a party
      parameters:
      - description: Party ID
        in: query
        name: ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/models.Party'
      security:
      - Bearer: []
      summary: Join a party
      tags:
      - Party
  /party/login:
    post:
      consumes:
      - application/json
      description: Login to the server using a Discord identify token, a Minecraft
        username and a Mojang session hash
      parameters:
      - description: Discord identify token
        in: body
        name: token
        required: true
        schema:
          type: string
      - description: Minecraft username
        in: body
        name: username
        required: true
        schema:
          type: string
      - description: Mojang session hash
        in: body
        name: hash
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Authentication'
      summary: Login to the server
      tags:
      - Party
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
