version: 1

labels:
  - label: 'bug'
    title: '(?i)\[?bug[:\]]'

  - label: 'feature'
    title: '(?i)\[?(feature|feat)[:\]]'

  - label: 'refactor'
    title: '(?i)\[?(refactor|ref)[:\]]'
    
  - label: 'critial'
    title: '(?i)\[?(critical|urgent)[:\]]'

  - label: 'triage'
    title: '.*'
    mergeable: false