name: Docker CI

on:
  push:
    tags:
      - '*'
        
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOCKER_USERNAME: edouard127
  DOCKER_IMAGE: lambda-rpc

jobs:
  build:
    name: Build Lambda RPC
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.1
          check-latest: true

      - name: Get Short Commit Hash
        id: vars
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        
      - name: Install swagger
        run: |
          go get -v -u github.com/swaggo/swag/cmd/swag
          go install github.com/swaggo/swag/cmd/swag
          
      - name: Generate code
        run: go generate ./...

      - name: Build Lambda RPC
        run: go build -o bin/main .

      - name: Upload Lambda RPC
        uses: actions/upload-artifact@v4.3.6
        with:
          name: lambda-rpc-${{ github.ref_name }}
          path: bin/main
          
      - name: Generate Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v4.1.1
        with:
          commitMode: true
          configurationJson: |
            {
              "pr_template": "- #{{TITLE}} [#{{AUTHOR}}](#{{URL}})"
            }

      - name: Create Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          name: Lambda ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changelog }}
          prerelease: false
          files: |
            bin/main
  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:${{ github.ref_name }}
          
      - name: Build and push (latest)
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:latest